import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { getCorsHeaders } from "../_shared/cors.ts";
import { anthropicCall } from "../_shared/anthropic.ts";

const GITHUB_API = "https://api.github.com";

async function githubFetch(url: string) {
  const headers: Record<string, string> = {
    Accept: "application/vnd.github.v3+json",
    "User-Agent": "SourceKit-App",
  };
  const token = Deno.env.get("GITHUB_TOKEN");
  if (token) {
    headers["Authorization"] = `Bearer ${token}`;
  }
  const res = await fetch(url, { headers });
  if (!res.ok) {
    if (res.status === 403 || res.status === 429) {
      const remaining = res.headers.get("x-ratelimit-remaining");
      if (remaining === "0") {
        const resetAt = res.headers.get("x-ratelimit-reset");
        const resetTime = resetAt ? new Date(Number(resetAt) * 1000).toISOString() : "unknown";
        console.error(`GitHub API rate limited. Resets at ${resetTime}`);
        throw new Error(`GITHUB_RATE_LIMITED`);
      }
    }
    console.error(`GitHub API error: ${res.status} for ${url}`);
    return null;
  }
  return res.json();
}

// GenAI-related topic and description keywords
const AI_KEYWORDS = [
  "ai", "ml", "llm", "gpt", "genai", "generative-ai", "generative",
  "openai", "anthropic", "claude", "langchain", "llamaindex", "llama-index",
  "rag", "retrieval-augmented", "vector-database", "embedding",
  "agent", "agentic", "multi-agent", "autogen", "crewai", "langgraph",
  "prompt-engineering", "prompt", "chatbot", "copilot",
  "transformer", "diffusion", "stable-diffusion", "midjourney",
  "fine-tuning", "finetuning", "lora", "qlora",
  "huggingface", "hugging-face", "ollama", "vllm",
  "semantic-kernel", "dspy", "instructor",
  "pinecone", "weaviate", "chromadb", "chroma", "qdrant", "milvus",
  "guardrails", "evals", "evaluation", "ai-safety",
];

// Files that indicate GenAI framework usage
const AI_FRAMEWORK_FILES: Record<string, string> = {
  "langchain": "LangChain",
  "llamaindex": "LlamaIndex",
  "llama_index": "LlamaIndex",
  "openai": "OpenAI SDK",
  "anthropic": "Anthropic SDK",
  "crewai": "CrewAI",
  "autogen": "AutoGen",
  "semantic_kernel": "Semantic Kernel",
  "dspy": "DSPy",
  "instructor": "Instructor",
  "guardrails": "Guardrails AI",
  "pinecone": "Pinecone",
  "weaviate": "Weaviate",
  "chromadb": "ChromaDB",
  "qdrant": "Qdrant",
  "vllm": "vLLM",
  "ollama": "Ollama",
  "transformers": "HuggingFace Transformers",
  "diffusers": "HuggingFace Diffusers",
  "haystack": "Haystack",
  "embedchain": "Embedchain",
  "mem0": "Mem0",
  "lancedb": "LanceDB",
  "marvin": "Marvin",
  "mirascope": "Mirascope",
  "pydantic_ai": "Pydantic AI",
  "pydantic-ai": "Pydantic AI",
  "claude_agent_sdk": "Claude Agent SDK",
  "claude-agent-sdk": "Claude Agent SDK",
};

// AI-assisted coding tool indicators
const AI_CODING_TOOL_FILES: Record<string, string> = {
  ".cursor": "Cursor",
  ".cursorignore": "Cursor",
  ".cursorrules": "Cursor",
  ".github/copilot": "GitHub Copilot",
  "copilot-instructions.md": "GitHub Copilot",
  ".windsurfrules": "Windsurf",
  "CLAUDE.md": "Claude Code",
  ".claude": "Claude Code",
  ".aider.conf.yml": "Aider",
  ".aider.input.history": "Aider",
  "cline_docs": "Cline",
  ".cline": "Cline",
  ".continue": "Continue",
};

// Claude Code commit patterns
const CLAUDE_CODE_PATTERN = /claude\.ai\/code\/session_|Co-authored-by:.*claude/i;
const AI_ASSISTED_PATTERNS = [
  CLAUDE_CODE_PATTERN,
  /generated by|auto-generated|ai-generated/i,
  /\bcopilot\b/i,
  /\bcursor\b.*\bgenerat/i,
];

interface RepoSignals {
  name: string;
  fullName: string;
  stars: number;
  forks: number;
  language: string | null;
  hasReadme: boolean;
  hasLicense: boolean;
  hasCI: boolean;
  hasTests: boolean;
  hasLinting: boolean;
  hasTypeChecking: boolean;
  openIssues: number;
  description: string | null;
  topics: string[];
  defaultBranch: string;
  updatedAt: string;
  createdAt: string;
  isAiRepo: boolean;
  aiFrameworks: string[];
  aiCodingTools: string[];
  hasClaudeCodeConfig: boolean;
}

interface CommitQuality {
  total: number;
  withGoodMessages: number;
  averageMessageLength: number;
  claudeCodeCommits: number;
  aiAssistedCommits: number;
}

interface AiSignals {
  genaiRepoCount: number;
  aiFrameworksDetected: string[];
  claudeCodeUsage: boolean;
  aiCodingTools: string[];
  recentAiActivity: boolean;
}

interface CodeQualityReport {
  username: string;
  overallScore: number;
  dimensions: {
    aiMastery: number;
    buildVelocity: number;
    tooling: number;
    testing: number;
    documentation: number;
    communityHealth: number;
  };
  repoBreakdown: {
    name: string;
    score: number;
    signals: string[];
    concerns: string[];
  }[];
  commitQuality: CommitQuality;
  summary: string;
  strengths: string[];
  improvements: string[];
  aiSignals: AiSignals;
}

function isAiRelated(repoData: any): boolean {
  const topics = (repoData.topics || []).map((t: string) => t.toLowerCase());
  const desc = (repoData.description || "").toLowerCase();
  const name = (repoData.name || "").toLowerCase();

  return AI_KEYWORDS.some(
    (kw) =>
      topics.includes(kw) ||
      desc.includes(kw) ||
      name.includes(kw)
  );
}

function detectAiFrameworks(files: string[]): string[] {
  const found = new Set<string>();
  for (const file of files) {
    const lower = file.toLowerCase();
    for (const [pattern, label] of Object.entries(AI_FRAMEWORK_FILES)) {
      if (lower.includes(pattern)) {
        found.add(label);
      }
    }
    // Check requirements.txt, package.json, pyproject.toml content names
    if (
      lower === "requirements.txt" ||
      lower === "pyproject.toml" ||
      lower === "setup.py" ||
      lower === "setup.cfg" ||
      lower === "package.json" ||
      lower === "cargo.toml"
    ) {
      // We flag these as needing deeper inspection but cant read contents via tree
      // The file presence at root is already captured elsewhere
    }
  }
  return Array.from(found);
}

function detectAiCodingTools(files: string[]): string[] {
  const found = new Set<string>();
  for (const file of files) {
    const lower = file.toLowerCase();
    for (const [pattern, label] of Object.entries(AI_CODING_TOOL_FILES)) {
      if (lower === pattern.toLowerCase() || lower.startsWith(pattern.toLowerCase())) {
        found.add(label);
      }
    }
  }
  return Array.from(found);
}

async function getRepoSignals(owner: string, repo: string, repoData: any): Promise<RepoSignals> {
  const contents = await githubFetch(
    `${GITHUB_API}/repos/${owner}/${repo}/contents`
  );
  const files = Array.isArray(contents) ? contents.map((f: any) => f.name) : [];
  const filesLower = files.map((f: string) => f.toLowerCase());

  const hasReadme = filesLower.some((f: string) => f.startsWith("readme"));
  const hasLicense = filesLower.some((f: string) => f === "license" || f === "license.md" || f === "license.txt");

  const hasCI = filesLower.includes(".github") ||
    filesLower.includes(".circleci") ||
    filesLower.includes(".travis.yml") ||
    filesLower.includes("jenkinsfile") ||
    filesLower.includes(".gitlab-ci.yml");

  const hasTests = filesLower.some(
    (f: string) =>
      f === "test" || f === "tests" || f === "__tests__" ||
      f === "spec" || f === "specs" ||
      f.startsWith("test.") || f.startsWith("test_") ||
      f.endsWith(".test.js") || f.endsWith(".test.ts") || f.endsWith(".test.tsx") ||
      f.endsWith(".spec.js") || f.endsWith(".spec.ts") || f.endsWith(".spec.tsx") ||
      f === "vitest.config.ts" || f === "jest.config.js" || f === "jest.config.ts" ||
      f === "pytest.ini" || f === ".pytest.ini" ||
      f === "karma.conf.js" || f === "cypress.json" || f === "cypress.config.ts"
  );

  const hasLinting = filesLower.some(
    (f: string) =>
      f.startsWith(".eslint") || f.startsWith("eslint") ||
      f === ".prettierrc" || f === "prettier.config.js" ||
      f === ".flake8" || f === "pylintrc" || f === ".pylintrc" ||
      f === "rubocop.yml" || f === ".rubocop.yml" ||
      f === ".golangci.yml" || f === "clippy.toml" ||
      f === "biome.json" || f === "biome.jsonc" ||
      f === ".editorconfig"
  );

  const hasTypeChecking = filesLower.some(
    (f: string) =>
      f === "tsconfig.json" || f.startsWith("tsconfig.") ||
      f === "mypy.ini" || f === ".mypy.ini" ||
      f === "pyrightconfig.json" ||
      f === "flow-typed" || f === ".flowconfig"
  );

  const aiRepo = isAiRelated(repoData);
  const aiFrameworks = detectAiFrameworks(files);
  const aiCodingTools = detectAiCodingTools(files);
  const hasClaudeCodeConfig = files.some(
    (f: string) => f === "CLAUDE.md" || f === ".claude" || f.toLowerCase() === "claude.md"
  );

  return {
    name: repoData.name,
    fullName: repoData.full_name,
    stars: repoData.stargazers_count,
    forks: repoData.forks_count,
    language: repoData.language,
    hasReadme,
    hasLicense,
    hasCI,
    hasTests,
    hasLinting,
    hasTypeChecking,
    openIssues: repoData.open_issues_count,
    description: repoData.description,
    topics: repoData.topics || [],
    defaultBranch: repoData.default_branch,
    updatedAt: repoData.updated_at,
    createdAt: repoData.created_at,
    isAiRepo: aiRepo,
    aiFrameworks,
    aiCodingTools,
    hasClaudeCodeConfig,
  };
}

function scoreRepo(signals: RepoSignals): { score: number; positives: string[]; concerns: string[] } {
  let score = 0;
  const positives: string[] = [];
  const concerns: string[] = [];

  const daysSinceUpdate = Math.floor(
    (Date.now() - new Date(signals.updatedAt).getTime()) / (1000 * 60 * 60 * 24)
  );

  // AI Mastery signals (35 pts)
  if (signals.isAiRepo) {
    score += 15;
    positives.push("GenAI project");
  }
  if (signals.aiFrameworks.length > 0) {
    score += Math.min(signals.aiFrameworks.length * 5, 15);
    positives.push(`Uses ${signals.aiFrameworks.join(", ")}`);
  }
  if (signals.hasClaudeCodeConfig) {
    score += 5;
    positives.push("Claude Code configured");
  }
  if (signals.aiCodingTools.length > 0 && !signals.hasClaudeCodeConfig) {
    score += 3;
    positives.push(`AI coding: ${signals.aiCodingTools.join(", ")}`);
  }
  if (!signals.isAiRepo && signals.aiFrameworks.length === 0) {
    concerns.push("No GenAI signals detected");
  }

  // Recency and velocity (25 pts)
  if (daysSinceUpdate < 14) {
    score += 15;
    positives.push("Active in last 2 weeks");
  } else if (daysSinceUpdate < 30) {
    score += 10;
    positives.push("Active in last month");
  } else if (daysSinceUpdate < 90) {
    score += 5;
    positives.push("Active in last quarter");
  } else {
    concerns.push(`Inactive for ${daysSinceUpdate} days`);
  }

  const daysSinceCreation = Math.floor(
    (Date.now() - new Date(signals.createdAt).getTime()) / (1000 * 60 * 60 * 24)
  );
  if (daysSinceCreation < 90) {
    score += 10;
    positives.push("Recently created");
  } else if (daysSinceCreation < 180) {
    score += 5;
  }

  // Tooling (15 pts)
  if (signals.hasCI) { score += 5; positives.push("CI/CD configured"); }
  if (signals.hasLinting) { score += 4; positives.push("Linter configured"); }
  if (signals.hasTypeChecking) { score += 4; positives.push("Type checking enabled"); }
  if (signals.hasTests) { score += 2; positives.push("Has tests"); }

  // Documentation (10 pts)
  if (signals.hasReadme) { score += 5; positives.push("Has README"); }
  else { concerns.push("Missing README"); }
  if (signals.description) { score += 3; }
  if (signals.hasLicense) { score += 2; }

  // Community (10 pts)
  if (signals.stars >= 10) { score += 4; positives.push(`${signals.stars} stars`); }
  if (signals.forks >= 5) { score += 3; positives.push(`${signals.forks} forks`); }
  if (signals.topics.length >= 2) { score += 3; }

  // Language bonus (5 pts)
  if (signals.language) { score += 5; }

  return { score: Math.min(score, 100), positives, concerns };
}

function analyzeCommitMessages(commits: any[]): CommitQuality {
  if (!commits.length) return { total: 0, withGoodMessages: 0, averageMessageLength: 0, claudeCodeCommits: 0, aiAssistedCommits: 0 };

  let goodMessages = 0;
  let totalLength = 0;
  let claudeCodeCommits = 0;
  let aiAssistedCommits = 0;

  for (const commit of commits) {
    const msg = commit.commit?.message || "";
    totalLength += msg.length;

    // Detect Claude Code commits
    if (CLAUDE_CODE_PATTERN.test(msg)) {
      claudeCodeCommits++;
      aiAssistedCommits++;
    } else if (AI_ASSISTED_PATTERNS.some((p) => p.test(msg))) {
      aiAssistedCommits++;
    }

    const isGood =
      msg.length > 10 &&
      /^(feat|fix|docs|style|refactor|test|chore|build|ci|perf|revert|merge|add|update|remove|implement|improve|correct|resolve)[\s(:]/i.test(msg);
    if (isGood) goodMessages++;
  }

  return {
    total: commits.length,
    withGoodMessages: goodMessages,
    averageMessageLength: Math.round(totalLength / commits.length),
    claudeCodeCommits,
    aiAssistedCommits,
  };
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: getCorsHeaders(req) });
  }

  try {
    const url = new URL(req.url);
    const username = url.searchParams.get("username");

    if (!username) {
      return new Response(
        JSON.stringify({ error: 'Parameter "username" is required' }),
        { status: 400, headers: { ...getCorsHeaders(req), "Content-Type": "application/json" } }
      );
    }

    // Fetch repos (top 30 non-forked, sorted by updated date to prioritize recent work)
    const repos = await githubFetch(
      `${GITHUB_API}/users/${username}/repos?sort=updated&per_page=30`
    );
    if (!repos) {
      return new Response(
        JSON.stringify({ error: "User not found or GitHub API unavailable" }),
        { status: 404, headers: { ...getCorsHeaders(req), "Content-Type": "application/json" } }
      );
    }

    const ownedRepos = (repos as any[]).filter((r: any) => !r.fork).slice(0, 15);

    if (ownedRepos.length === 0) {
      return new Response(
        JSON.stringify({ error: "No owned repositories found" }),
        { status: 404, headers: { ...getCorsHeaders(req), "Content-Type": "application/json" } }
      );
    }

    // Analyze top repos in parallel (limit to 10 to capture more AI signal)
    const reposToAnalyze = ownedRepos.slice(0, 10);
    const signalResults = await Promise.all(
      reposToAnalyze.map((r: any) => getRepoSignals(username, r.name, r))
    );

    // Fetch recent commits from top 5 repos (more commits = better Claude Code detection)
    const commitPromises = reposToAnalyze.slice(0, 5).map((r: any) =>
      githubFetch(`${GITHUB_API}/repos/${username}/${r.name}/commits?per_page=30`)
    );
    const commitResults = await Promise.all(commitPromises);
    const allCommits = commitResults.flat().filter(Boolean);
    const commitQuality = analyzeCommitMessages(allCommits);

    // Also check for Claude Code in package dependency files of top repos
    const depCheckPromises = reposToAnalyze.slice(0, 3).map(async (r: any) => {
      const pkg = await githubFetch(`${GITHUB_API}/repos/${username}/${r.name}/contents/package.json`);
      if (pkg && pkg.content && pkg.encoding === "base64") {
        try {
          const decoded = atob(pkg.content.replace(/\n/g, ""));
          const lower = decoded.toLowerCase();
          const frameworks: string[] = [];
          if (lower.includes("@anthropic-ai/sdk") || lower.includes("claude")) frameworks.push("Anthropic SDK");
          if (lower.includes("openai")) frameworks.push("OpenAI SDK");
          if (lower.includes("langchain")) frameworks.push("LangChain");
          if (lower.includes("llamaindex")) frameworks.push("LlamaIndex");
          if (lower.includes("@pinecone-database")) frameworks.push("Pinecone");
          if (lower.includes("chromadb") || lower.includes("@chromadb")) frameworks.push("ChromaDB");
          if (lower.includes("ai-sdk") || lower.includes("@ai-sdk")) frameworks.push("Vercel AI SDK");
          return frameworks;
        } catch { return []; }
      }
      return [];
    });
    const depResults = await Promise.all(depCheckPromises);
    const depFrameworks = new Set(depResults.flat());

    // Also check Python requirements
    const pyCheckPromises = reposToAnalyze.slice(0, 3).map(async (r: any) => {
      const req = await githubFetch(`${GITHUB_API}/repos/${username}/${r.name}/contents/requirements.txt`);
      if (req && req.content && req.encoding === "base64") {
        try {
          const decoded = atob(req.content.replace(/\n/g, ""));
          const lower = decoded.toLowerCase();
          const frameworks: string[] = [];
          if (lower.includes("anthropic")) frameworks.push("Anthropic SDK");
          if (lower.includes("openai")) frameworks.push("OpenAI SDK");
          if (lower.includes("langchain")) frameworks.push("LangChain");
          if (lower.includes("llama-index") || lower.includes("llamaindex")) frameworks.push("LlamaIndex");
          if (lower.includes("crewai")) frameworks.push("CrewAI");
          if (lower.includes("autogen")) frameworks.push("AutoGen");
          if (lower.includes("pinecone")) frameworks.push("Pinecone");
          if (lower.includes("chromadb")) frameworks.push("ChromaDB");
          if (lower.includes("qdrant")) frameworks.push("Qdrant");
          if (lower.includes("transformers")) frameworks.push("HuggingFace Transformers");
          if (lower.includes("dspy")) frameworks.push("DSPy");
          if (lower.includes("instructor")) frameworks.push("Instructor");
          if (lower.includes("pydantic-ai") || lower.includes("pydantic_ai")) frameworks.push("Pydantic AI");
          return frameworks;
        } catch { return []; }
      }
      return [];
    });
    const pyResults = await Promise.all(pyCheckPromises);
    pyResults.flat().forEach((f) => depFrameworks.add(f));

    // Merge dependency-detected frameworks into signal results
    const allAiFrameworks = new Set<string>();
    for (const s of signalResults) {
      s.aiFrameworks.forEach((f) => allAiFrameworks.add(f));
    }
    depFrameworks.forEach((f) => allAiFrameworks.add(f));

    const allAiCodingTools = new Set<string>();
    for (const s of signalResults) {
      s.aiCodingTools.forEach((t) => allAiCodingTools.add(t));
    }

    // Score each repo
    const repoBreakdown = signalResults.map((signals) => {
      const { score, positives, concerns } = scoreRepo(signals);
      return { name: signals.name, score, signals: positives, concerns };
    });

    const n = signalResults.length;

    // AI Mastery dimension (heaviest weight)
    const aiRepoCount = signalResults.filter((s) => s.isAiRepo).length;
    const aiRepoRatio = aiRepoCount / n;
    const frameworkBreadth = Math.min(allAiFrameworks.size * 12, 50);
    const claudeCodeBonus = commitQuality.claudeCodeCommits > 0 ? 20 : 0;
    const aiCodingToolBonus = Math.min(allAiCodingTools.size * 8, 15);
    const hasClaudeConfig = signalResults.some((s) => s.hasClaudeCodeConfig);
    const claudeConfigBonus = hasClaudeConfig ? 15 : 0;
    const aiMastery = Math.min(
      Math.round(aiRepoRatio * 40 + frameworkBreadth + claudeCodeBonus + aiCodingToolBonus + claudeConfigBonus),
      100
    );

    // Build velocity dimension
    const recentRepos = signalResults.filter((s) => {
      const days = Math.floor((Date.now() - new Date(s.updatedAt).getTime()) / (1000 * 60 * 60 * 24));
      return days < 30;
    }).length;
    const recentRatio = recentRepos / n;
    const newRepos = signalResults.filter((s) => {
      const days = Math.floor((Date.now() - new Date(s.createdAt).getTime()) / (1000 * 60 * 60 * 24));
      return days < 180;
    }).length;
    const commitVolume = Math.min(allCommits.length * 2, 30);
    const buildVelocity = Math.min(
      Math.round(recentRatio * 40 + (newRepos / n) * 30 + commitVolume),
      100
    );

    // Tooling dimension
    let toolingSum = 0;
    for (const s of signalResults) {
      toolingSum += (s.hasCI ? 30 : 0) + (s.hasLinting ? 25 : 0) + (s.hasTypeChecking ? 25 : 0);
      // AI coding tools count toward tooling
      toolingSum += Math.min(s.aiCodingTools.length * 10, 20);
    }
    const tooling = Math.min(Math.round(toolingSum / n), 100);

    // Testing dimension
    let testingSum = 0;
    for (const s of signalResults) {
      testingSum += s.hasTests ? 100 : 0;
    }
    const testing = Math.round(testingSum / n);

    // Documentation dimension
    let docSum = 0;
    for (const s of signalResults) {
      docSum += (s.hasReadme ? 50 : 0) + (s.description ? 30 : 0) + (s.hasLicense ? 20 : 0);
    }
    const documentation = Math.round(docSum / n);

    // Community Health dimension
    let communitySum = 0;
    for (const s of signalResults) {
      communitySum += Math.min((s.stars * 5) + (s.forks * 10) + (s.topics.length * 10), 100);
    }
    const communityHealth = Math.min(Math.round(communitySum / n), 100);

    const dimensions = {
      aiMastery,
      buildVelocity,
      tooling,
      testing,
      documentation,
      communityHealth,
    };

    // Commit quality bonus: weight Claude Code commits heavily
    const commitBonus = commitQuality.total > 0
      ? Math.min(
          (commitQuality.claudeCodeCommits / commitQuality.total) * 15 +
          (commitQuality.withGoodMessages / commitQuality.total) * 5,
          15
        )
      : 0;

    // Overall score: AI Mastery is dominant
    const overallScore = Math.min(
      Math.round(
        (dimensions.aiMastery * 0.30) +
        (dimensions.buildVelocity * 0.20) +
        (dimensions.tooling * 0.15) +
        (dimensions.testing * 0.10) +
        (dimensions.documentation * 0.08) +
        (dimensions.communityHealth * 0.07) +
        commitBonus
      ),
      100
    );

    // Aggregate AI signals
    const aiSignals: AiSignals = {
      genaiRepoCount: aiRepoCount,
      aiFrameworksDetected: Array.from(allAiFrameworks),
      claudeCodeUsage: commitQuality.claudeCodeCommits > 0 || hasClaudeConfig,
      aiCodingTools: Array.from(allAiCodingTools),
      recentAiActivity: signalResults.some((s) => {
        const days = Math.floor((Date.now() - new Date(s.updatedAt).getTime()) / (1000 * 60 * 60 * 24));
        return s.isAiRepo && days < 30;
      }),
    };

    // Build context for Claude AI summary
    const repoSummary = repoBreakdown
      .map((r) => `${r.name} (${r.score}/100): +[${r.signals.join(", ")}] -[${r.concerns.join(", ")}]`)
      .join("\n");

    const aiPrompt = `You are evaluating a GitHub developer as a potential Technical Builder at AI Fund, a venture studio founded by Andrew Ng. The role requires hands-on GenAI building, rapid prototyping, and deep familiarity with the latest AI tools and frameworks.

Username: ${username}
Overall Score: ${overallScore}/100

Dimension Scores:
- AI Mastery: ${dimensions.aiMastery}
- Build Velocity: ${dimensions.buildVelocity}
- Tooling: ${dimensions.tooling}
- Testing: ${dimensions.testing}
- Documentation: ${dimensions.documentation}
- Community: ${dimensions.communityHealth}

AI Signals:
- GenAI repos: ${aiSignals.genaiRepoCount} of ${n}
- Frameworks detected: ${aiSignals.aiFrameworksDetected.join(", ") || "None"}
- Claude Code usage: ${aiSignals.claudeCodeUsage ? "Yes" : "No"}
- AI coding tools: ${aiSignals.aiCodingTools.join(", ") || "None"}
- Recent AI activity (last 30 days): ${aiSignals.recentAiActivity ? "Yes" : "No"}

Commit Quality: ${commitQuality.withGoodMessages}/${commitQuality.total} well-formatted, ${commitQuality.claudeCodeCommits} from Claude Code, ${commitQuality.aiAssistedCommits} AI-assisted

Repository Breakdown:
${repoSummary}

Write a direct, no-nonsense assessment. Focus on their fit as a fast-moving GenAI builder. Call out specific frameworks and patterns you see. Do not use emojis or em dashes. Keep it blunt and useful.

Respond with ONLY valid JSON (no markdown, no backticks):
{
  "summary": "2-3 sentence assessment focused on their GenAI building capability and velocity",
  "strengths": ["strength 1", "strength 2", "strength 3"],
  "improvements": ["gap 1", "gap 2"]
}`;

    let summary = "";
    let strengths: string[] = [];
    let improvements: string[] = [];

    try {
      const aiResult = await anthropicCall(
        "You are a technical recruiter at AI Fund evaluating developers for a Technical Builder role. You care about GenAI depth, build speed, and modern tooling. Be direct. No emojis. No em dashes. No filler.",
        aiPrompt,
        { maxTokens: 512 }
      );

      const parsed = JSON.parse(aiResult);
      summary = parsed.summary || "";
      strengths = parsed.strengths || [];
      improvements = parsed.improvements || [];
    } catch (aiError) {
      console.error("AI analysis failed, using fallback:", aiError);
      const aiFrameworkList = Array.from(allAiFrameworks);
      if (aiRepoCount > 0) {
        summary = `Analyzed ${n} repositories. Found ${aiRepoCount} GenAI-related projects${aiFrameworkList.length > 0 ? ` using ${aiFrameworkList.slice(0, 3).join(", ")}` : ""}. Overall builder score: ${overallScore}/100.`;
      } else {
        summary = `Analyzed ${n} repositories. No clear GenAI building activity detected. Score: ${overallScore}/100.`;
      }
      strengths = repoBreakdown.flatMap((r) => r.signals).slice(0, 3);
      if (strengths.length === 0) strengths = ["Active GitHub presence"];
      improvements = [];
      if (aiRepoCount === 0) improvements.push("No GenAI projects found");
      if (!aiSignals.claudeCodeUsage) improvements.push("No Claude Code usage detected");
      if (improvements.length === 0) improvements = repoBreakdown.flatMap((r) => r.concerns).slice(0, 2);
    }

    const report: CodeQualityReport = {
      username,
      overallScore,
      dimensions,
      repoBreakdown,
      commitQuality,
      summary,
      strengths,
      improvements,
      aiSignals,
    };

    return new Response(JSON.stringify(report), {
      headers: { ...getCorsHeaders(req), "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Error in github-code-quality:", error);
    if (error instanceof Error && error.message === "GITHUB_RATE_LIMITED") {
      return new Response(
        JSON.stringify({ error: "GitHub API rate limit exceeded. Try again later." }),
        { status: 429, headers: { ...getCorsHeaders(req), "Content-Type": "application/json" } }
      );
    }
    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      { status: 500, headers: { ...getCorsHeaders(req), "Content-Type": "application/json" } }
    );
  }
});
